namespace DynamicFontAtlasLib.Internal.TrueType.Enums;

public enum NameId : ushort {
    CopyrightNotice = 0,
    FamilyName = 1,
    SubfamilyName = 2,
    UniqueId = 3,
    FullFontName = 4,
    VersionString = 5,
    PostScriptName = 6,
    Trademark = 7,
    Manufacturer = 8,
    Designer = 9,
    Description = 10,
    UrlVendor = 11,
    UrlDesigner = 12,
    LicenseDescription = 13,
    LicenseInfoUrl = 14,
    TypographicFamilyName = 16,
    TypographicSubfamilyName = 17,
    CompatibleFullMac = 18,
    SampleText = 19,
    PoscSriptCidFindFontName = 20,
    WwsFamilyName = 21,
    WwsSubfamilyName = 22,
    LightBackgroundPalette = 23,
    DarkBackgroundPalette = 24,
    VariationPostScriptNamePrefix = 25,
}
